make e2e more error prone

diff --git a/.github/workflows/test_e2e.yml b/.github/workflows/test_e2e.yml
--- a/.github/workflows/test_e2e.yml
+++ b/.github/workflows/test_e2e.yml
@@ -65,7 +65,6 @@ jobs:
 
       - name: Transfer funds to Test accounts
         run: |
-          ## Sleep 5 Seconds
           sleep 5
           curl --silent --location --request GET 'localhost:26657/status' | jq '.'
 
@@ -80,17 +79,31 @@ jobs:
             --gas-prices=0.025basetcro \
             --keyring-backend test \
             --chain-id testnet \
+            --broadcast-mode sync \
             -y --output json | jq '.'
+          if [[ $(echo $RESULT | jq '.code') -ne 0 ]]; then
+            echo "failed to transfer 100tcro from ecosystem to tcro1n0jfe772qx5svnme9y2gl75u85luxfjnhkacy0"
+            exit 1
+          fi
+          
+          # # Wait for the transaction to be included in a block
+          # sleep 5
 
           ## TRANSFER 100CRO FROM "ecosystem" to "tcro17c6rn92lnw0d8ct37mlycdaeau4f9hm569ef9s"
-          ./build/chain-maind tx bank send \
+          RESULT=$(./build/chain-maind tx bank send \
             $(./build/chain-maind keys show ecosystem -a --keyring-backend test) \
             tcro17c6rn92lnw0d8ct37mlycdaeau4f9hm569ef9s \
             100tcro \
             --gas-prices=0.025basetcro \
             --keyring-backend test \
             --chain-id testnet \
-            -y --output json | jq '.'
+            --broadcast-mode sync \
+            -y --output json | jq '.')
+          echo $RESULT
+          if [[ $(echo $RESULT | jq '.code') -ne 0 ]]; then
+            echo "failed to transfer 100tcro from ecosystem to tcro17c6rn92lnw0d8ct37mlycdaeau4f9hm569ef9s"
+            exit 1
+          fi
 
           ## TRANSFER 10CRO FROM "reserve" to "tcro1c5nd9l5ylh8udw5lsfs0hlvzxwrlymxqlnl266"
           ./build/chain-maind tx bank send \
@@ -100,7 +113,12 @@ jobs:
             --gas-prices=0.025basetcro \
             --keyring-backend test \
             --chain-id testnet \
+            --broadcast-mode sync \
             -y --output json | jq '.'
+          if [[ $(echo $RESULT | jq '.code') -ne 0 ]]; then
+            echo "failed to transfer 100tcro from reserve to tcro1c5nd9l5ylh8udw5lsfs0hlvzxwrlymxqlnl266"
+            exit 1
+          fi
 
       - name: Checkout this project
         uses: actions/checkout@v2
